---
- name: Install Windows Software via Chocolatey
  hosts: windows
  tasks:
    - name: Install Chocolatey packages
      win_chocolatey:
        name:
          - 7zip
          - git
          - notepadplusplus
        state: present
